MusicEShopApplication/MusicEShop.Web/Controllers/AlbumsController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicEShop.Domain.DomainModels;
using MusicEShop.Service.Interface;

namespace MusicEShop.Web.Controllers
{
    [Authorize]
    public class AlbumsController : Controller
    {
        private readonly IBookingService _bookingService;
        private readonly IAlbumService _albumService;
        private readonly IArtistService _artistService;
        private readonly ICartService _cartService;
        public AlbumsController(IAlbumService albumService, IArtistService artistService, ICartService cartService, IBookingService bookingService)
        {
            _albumService = albumService;
            _artistService = artistService;
            _cartService = cartService;
            _bookingService = bookingService;
        }
        public IActionResult Index()
        {
            var albums = _albumService.GetAllAlbums();
            foreach (var album in albums)
            {
                album.Artist = _artistService.GetArtistById(album.ArtistId);
            }

            return View(albums);
        }

        public  IActionResult External()
        {
            var bookings = _bookingService.GetAllBookings();
           

            return View(bookings);
        }
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = _albumService.GetAlbumById(id);

            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["ArtistId"] = new SelectList(_artistService.GetAllArtists(), "Id", "Name");
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Title,Genre,Details,ReleaseDate,CoverImage,Price,ArtistId,Id")] Album album)
        {
            if (ModelState.IsValid)
            {
                album.Id = Guid.NewGuid();

          
                _albumService.CreateAlbum(album);

                return RedirectToAction(nameof(Index));
            }

            ViewData["ArtistId"] = new SelectList(_artistService.GetAllArtists(), "Id", "Id", album.ArtistId);
            return View(album);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult  Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = _albumService.GetAlbumById(id);
            if (album == null)
            {
                return NotFound();
            }
            ViewData["ArtistId"] = new SelectList(_artistService.GetAllArtists(), "Id", "Name", album.ArtistId);
            return View(album);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Guid id, [Bind("Title,Genre,Details,ReleaseDate,Price,CoverImage,ArtistId,Id")] Album album)
        {
            if (id != album.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _albumService.UpdateAlbum(album);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlbumExists(album.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_artistService.GetAllArtists(), "Id", "Name", album.ArtistId);
            return View(album);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = _albumService.GetAlbumById(id);
            if (album == null)
            {
                return NotFound();
            }
            return View(album);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var album = _albumService.GetAlbumById(id);
            if (album != null)
            {
                _albumService.DeleteAlbum(id);
            }

            return RedirectToAction(nameof(Index));
        }
        public IActionResult ListAlbumsByArtist(Guid artistId)
        {
            var albums = _albumService.GetAlbumsByArtist(artistId);

            if (albums == null || !albums.Any())
            {
                return NotFound("No albums found for this artist.");
            }

            return View(albums);
        }

        public IActionResult AddToCart(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = _albumService.GetAlbumById(id);

            CartItem ps = new CartItem();

            ps.Quantity = 1;

            if (album != null)
            {
                ps.AlbumId = album.Id;
            }

            return View(ps);
        }

        [HttpPost]
        public IActionResult AddToCartConfirmed(CartItem model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            _cartService.AddToShoppingConfirmed(model, userId);



            return View("Index", _albumService.GetAllAlbums());
        }


        private bool AlbumExists(Guid id)
        {
            return _albumService.GetAllAlbums().Any(e => e.Id == id);
        }
    }
}

MusicEShopApplication/MusicEShop.Web/Controllers/ExportController.cs
using System.Security.Claims;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using MusicEShop.Service.Interface;

namespace MusicEShop.Web.Controllers
{
    public class ExportController : Controller
    {
        private readonly IOrderService _orderService;
        public ExportController(IOrderService orderService)
        {
            _orderService = orderService;
        }
        public FileContentResult ExportAllOrders()
        {
            string fileName = "Orders.xlsx";
            string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            using (var workbook = new XLWorkbook())
            {
                IXLWorksheet worksheet = workbook.Worksheets.Add("Orders");
                worksheet.Cell(1, 1).Value = "OrderID";
                worksheet.Cell(1, 2).Value = "Customer UserName";
                worksheet.Cell(1, 3).Value = "Total Price";
                var data = _orderService.GetAllOrders().Where(o => o.UserId == currentUserId).ToList();
                for (int i = 0; i < data.Count(); i++)
                {
                    var item = data[i];
                    worksheet.Cell(i + 2, 1).Value = item.Id.ToString();
                    worksheet.Cell(i + 2, 2).Value = User.FindFirstValue(ClaimTypes.Name);
                    var total = 0;
                    for (int j = 0; j < item.OrderItems.Count(); j++)
                    {
                        worksheet.Cell(1, 4 + j).Value = "Product - " + (j + 1);
                        var orderItem = item.OrderItems.ElementAt(j);
                        worksheet.Cell(i + 2, 4 + j).Value = orderItem.Album != null ? orderItem.Album.Title : orderItem.Track.Title;
                        total += (int)(orderItem.Quantity * (orderItem.Album != null ? orderItem.Album.Price : orderItem.Track.Price));

                    }

                    worksheet.Cell(i + 2, 3).Value = total;
                }
                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(content, contentType, fileName);
                }
            }
        }
    }
}

MusicEShopApplication/MusicEShop.Web/Controllers/TracksController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicEShop.Domain.DomainModels;
using MusicEShop.Repository;
using MusicEShop.Service.Interface;

namespace MusicEShop.Web.Controllers
{
    [Authorize]
    public class TracksController : Controller
    {
        private readonly ITrackService _trackService;
        private readonly IAlbumService _albumService;
        private readonly ICartService _cartService;

        public TracksController(ITrackService trackService, IAlbumService albumService, ICartService cartService)
        {
            this._trackService = trackService;
            _albumService = albumService;
            _cartService = cartService;
        }

        public IActionResult Index()
        {

            var tracks=_trackService.GetAllTracks();
            
            
            return View(tracks);
        }

        public IActionResult Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var track = _trackService.GetTrackById(id);
            if (track == null)
            {
                return NotFound();
            }

            return View(track);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["AlbumId"] = new SelectList(_albumService.GetAllAlbums(), "Id", "Title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create([Bind("Title,Duration,Price,AlbumId,Id")] Track track)
        {
            if (ModelState.IsValid)
            {
                track.Id = Guid.NewGuid();
                track.Album=_albumService.GetAlbumById(track.AlbumId);
                _trackService.CreateTrack(track);
                
                return RedirectToAction(nameof(Index));
            }
            ViewData["AlbumId"] = new SelectList(_albumService.GetAllAlbums(), "Id", "Title", track.AlbumId);
            return View(track);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var track = _trackService.GetTrackById(id);
            if (track == null)
            {
                return NotFound();
            }
            ViewData["AlbumId"] = new SelectList(_albumService.GetAllAlbums(), "Id", "Title", track.AlbumId);
            return View(track);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Guid id, [Bind("Title,Duration,Price,AlbumId,Id")] Track track)
        {
            if (id != track.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _trackService.UpdateTrack(track);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrackExists(track.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AlbumId"] = new SelectList(_albumService.GetAllAlbums(), "Id", "Title", track.AlbumId);
            return View(track);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var track = _trackService.GetTrackById(id);
            if (track == null)
            {
                return NotFound();
            }

            return View(track);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var track = _trackService.GetTrackById(id);
            if (track != null)
            {
                _trackService.DeleteTrack(id);  
            }

            return RedirectToAction(nameof(Index));
        }
        public IActionResult AddToCart(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var track = _trackService.GetTrackById(id);

            CartItem ps = new CartItem();

            ps.Quantity = 1;

            if (_trackService != null)
            {
                ps.TrackId = track.Id;
            }

            return View(ps);
        }

        [HttpPost]
        public IActionResult AddToCartConfirmed(CartItem model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            _cartService.AddToShoppingConfirmed(model, userId);



            return RedirectToAction(nameof(Index));
        }
        private bool TrackExists(Guid id)
        {
            return _trackService.GetAllTracks().Any(e => e.Id == id);
        }
    }
}

MusicEShopApplication/MusicEShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicEShop.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MusicEShop.Web.styles.css" asp-append-version="true" />
</head>
<body class="@( ViewData["Title"] == "Home Page" ? "home-page" : "")">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3 bg-light-beige custom-navbar">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo-no-background.png" alt="MusicEShop Logo" class="logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Albums" asp-action="Index">Albums</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Artists" asp-action="Index">Artists</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Tracks" asp-action="Index">Tracks</a></li>
                        <li class="nav-item"><a class="nav-link1 btn btn-outline-danger" asp-area="" asp-controller="Albums" asp-action="External">Trips</a></li>
                    </ul>

                    <div class="d-flex align-items-center gap-3 me-3">
                        <a class="nav-link nav-icon-link" asp-area="" asp-controller="ShoppingCart" asp-action="Index">
                            <img src="~/img/shopping-cart-no-background.png" alt="Shopping Cart" class="nav-icon">
                        </a>
                        <a class="nav-link nav-icon-link" asp-area="" asp-controller="Export" asp-action="ExportAllOrders">
                            <img src="~/img/export-no-background.png" alt="Export Orders" class="nav-icon">
                        </a>

                      
                    </div>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="@( ViewData["Title"] == "Home Page" ? "display: none" : "")" class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MusicEShop.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>